antora:
  extensions:
    - ./lib/my-extension.js
site:
  title: InferenceQL
  start_page: start-page::start-page.adoc
content:
  sources:
    - url: ./
      start_path: docs
    - url: https://github.com/InferenceQL/inferenceql.query
      start_path: docs
    - url: git@github.com:InferenceQL/inferenceql.structure-learning.git
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
